### ISSUE TITLE
Wyśrodkować nawigację.

### ISSUE THREAD

**Issue by patryk1990s** [Seseikelele/Agora#8]

**Comment by Seseikelele** [comment]
teraz menu wisi jako jakieś dziwne <ul>
więc jest na 40% szerokości od lewej <ul> i od prawej na jakieś 10% ustawienia
rozpierdol to <ul> albo zrób, aby było tylko szerokości tych trzech przycisków (obecnie jest szersze) aby wyjściowo wyglądało w stylu:
<div o szer. x%><div z menu o szerokości 20%><div o szer. x%><ustawienia>

czytelne wchuj? kminisz co mam na myśli? :D
